### ISSUE TITLE
SQLite Tabellenaufbau

### ISSUE THREAD

**Issue by zaechjo** [zagolaha/TEC_Schnitzeljagd#7]
Aufbau der Tabellen mit den gespeicherten Werten. 
Welche Sachen sollen gespeichert werden? 

Ergebnisse einer Abfrage in einem Leaderboard darstellen

**Comment by zagolaha** [comment]
Die Table mit den Spalten ist schon erstellt. Sieht etwa so aus:
![table](https://github.com/zagolaha/TEC_Schnitzeljagd/assets/147156314/2ccb8ed4-92fd-4d4e-8e32-7d5e00a9829c)
